name: Build
on:
  push:
    branches:
     - 'main'
     - 'cicd'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Git informatioon
      id: git_info
      shell: bash
      run: |
        echo ::set-output name=GIT_TAG::${GITHUB_REF#refs/*/}
        echo ::set-output name=GIT_COMMIT::$(git rev-parse --short HEAD)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build application in Docker builder stage
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        target: builder
        build-args: |
          "GIT_COMMIT=${{ steps.git_info.outputs.GIT_COMMIT }}"
          "GIT_TAG=${{ steps.git_info.outputs.GIT_TAG }}"
