name: Build binary
on:
  push:
    branches:
     - 'main'
     - 'cicd'

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build application in Docker builder stage
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        target: builder