name: Release new version
on:
  push:
    tags:
     - '*'

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Git informatioon
      id: git_info
      shell: bash
      run: |
        echo ::set-output name=GIT_TAG::${GITHUB_REF#refs/*/}
        echo ::set-output name=GIT_COMMIT::$(git rev-parse --short HEAD)

    - name: Publish to Registry
      id: publish_to_registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        GIT_COMMIT: ${{ steps.git_info.outputs.GIT_COMMIT }}
        GIT_TAG: ${{ steps.git_info.outputs.GIT_TAG }}
      with:
        name: dreitier/silencer
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        tag_names: true
        buildargs: GIT_COMMIT,GIT_TAG

    - name: Extract binary image from previously build docker image
      id: extract
      uses: shrink/actions-docker-extract@v1
      with:
        image: 'dreitier/silencer:${{ steps.publish_to_registry.outputs.tag }}'
        path: '/app/silencer'

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: silencer
        path: ${{ steps.extract.outputs.destination }}
